spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${OAUTH_REDIRECT_URI}
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

          google-admin:
            redirect-uri: ${OAUTH_REDIRECT_URI_ADMIN}
            client-id: ${OAUTH_CLIENT_ID_ADMIN}
            client-secret: ${OAUTH_CLIENT_SECRET_ADMIN}
            scope:
              - email
              - profile