spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PW}
  jwt:
    issuer: 'jwt'
    secret-key: ${SECRET_KEY}
    access-exp: 360000000
    refresh-exp: 8640000
  profiles:
    include: oauth, aws
  upload:
    dir: ${UPLOAD_DIR}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
toss:
  api_secret: ${TOSS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

  metrics:
    enable:
      jvm: true
      processor: false