spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${OAUTH_REDIRECT_URI}
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile